# Generated by Django 5.2.9 on 2026-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional total time limit for the whole quiz, in minutes. Leave blank for no timer. The timer starts when the user begins their attempt.', null=True),
        ),
    ]
