# Generated by Django 5.2.9 on 2026-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time_limit_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
